print("hello python!")

def getZero(num):
	if num<10:
		return '0'+str(num)
	return str(num)

import random

howMuch = 5

f = open("ConstraintsJSON_"+str(howMuch)+".json", "w")
f.write('[')

idi = -1

for i in range(0,howMuch):
	idi += 1
	f.write('{')
	f.write('\n')
	f.write('"id": '+str(idi)+',')
	f.write('\n')
	f.write('"nstraintName": "nesto",')
	f.write('\n')
	f.write('"setValue": 3.2,')
	f.write('\n')
	f.write('"maxHours": "nesto",')
	f.write('\n')
	f.write('"startDate": "2019-06-06T00:00:00",')
	f.write('\n')
	f.write('"endDate": "2019-06-06T00:00:00",')
	f.write('\n')
	f.write('"isNightWorker": false,')
	f.write('\n')
	f.write('"comparationMode": "departman",')
	f.write('\n')
	f.write('"comparationValue": "departman",')
	f.write('\n')
	f.write('"constraintRule": {')
	f.write('\n')
	f.write('  "id": 2,')
	f.write('\n')
	f.write('  "name": "nesto",')
	f.write('\n')
	f.write(' "isNotAlreadyAssigned": false,')
	f.write('\n')
	f.write(' "isEmployeeLeaverStatus": false,')
	f.write('\n')
	f.write('  "isEmployeePlannedAbsence": false,')
	f.write('\n')
	f.write('  "isEmployeeAvailability": false,')
	f.write('\n')
	f.write('  "isMaximumNumberOfHours": false,')
	f.write('\n')
	f.write('  "isEmployeeMustWorkWithEmployee": false,')
	f.write('\n')
	f.write('  "isEmployeeMustNotWorkWithEmployee": false,')
	f.write('\n')
	f.write('  "isMaximumDaysOfWeek": false,')
	f.write('\n')
	f.write('  "isMaximumJobTypes": false,')
	f.write('\n')
	f.write('  "isMaximumJobTimes": false,')
	f.write('\n')
	f.write('  "isMaximumJobTypesConsecutivly": false,')
	f.write('\n')
	f.write('  "isMustNotWorkForTimePeriodAfterJobType": false,')
	f.write('\n')
	f.write('  "isMaximumNumberOfAverageHoursInPeriod": false,')
	f.write('\n')
	f.write('  "isDaysOffWithinnPeriod": false,')
	f.write('\n')
	f.write('  "isSplitShift": false,')
	f.write('\n')
	f.write('  "isNightWorkerMinimumAge": false,')
	f.write('\n')
	f.write('  "isEmployeeFieldValue": false,')
	f.write('\n')
	f.write('  "isEmployeeRoster": false')
	f.write('\n')
	f.write('}')
	f.write('\n')
	f.write('  },')
	f.write('\n')

	
f.write(']')

print("nesto")
f.close()
print("nesto")